### ISSUE TITLE
Not in list ValueError in keyboard teleop

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_ros#73]
When launched keyboard teleop using `roslaunch stretch_core keyboard_teleop.launch`, pressing the `c` key while the robot has the standard gripper configured will cause the node to emit the following error:

```
Traceback (most recent call last):
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/keyboard_teleop", line 436, in <module>
    node.main()
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/keyboard_teleop", line 413, in main
    self.send_command(command)
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/keyboard_teleop", line 331, in send_command
    joint_index = joint_state.name.index(joint_name)
ValueError: 'joint_wrist_pitch' is not in list
[keyboard_teleop-5] process has died [pid 3598, exit code 1, cmd /home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/keyboard_teleop __name:=keyboard_teleop __log:=/home/hello-robot/.ros/log/6e4d0110-2443-11ed-ba38-1c697a0e6523/keyboard_teleop-5.log].
log file: /home/hello-robot/.ros/log/6e4d0110-2443-11ed-ba38-1c697a0e6523/keyboard_teleop-5*.log
```

**Comment by hello-binit** [comment]
When launched keyboard teleop using `roslaunch stretch_core keyboard_teleop.launch`, pressing the `4` and `6` keys while the driver is in navigation mode will cause the node to emit the following error:

```
[ERROR] [1650075787.711150]: Exception in your execute callback: global name 'active_positioning_joint_names' is not defined
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/joint_trajectory_server.py", line 67, in execute_cb
    for c in self.command_groups]
  File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/command_groups.py", line 484, in update
    "Current mode = {1}.").format(active_positioning_joint_names, robot_mode)
NameError: global name 'active_positioning_joint_names' is not defined
```
